# Generated by Django 3.2.3 on 2021-11-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezerwacje', '0003_alter_onetimeverifycodeforemployeeregistration_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyCodeEmployeeRegistration',
            fields=[
                ('autoid', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=25, verbose_name='Kod weryfikujący rejestrację pracownika')),
            ],
        ),
        migrations.DeleteModel(
            name='OneTimeVerifyCodeForEmployeeRegistration',
        ),
    ]
