# Generated by Django 3.2.3 on 2021-12-01 20:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rezerwacje', '0004_auto_20211130_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifycodeemployeeregistration',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='verifycodeemployeeregistration',
            name='date_used',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='verifycodeemployeeregistration',
            name='code',
            field=models.CharField(max_length=25, unique=True, verbose_name='Kod weryfikujący rejestrację pracownika'),
        ),
        migrations.AlterField(
            model_name='verifycodeemployeeregistration',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
