# Generated by Django 3.2.3 on 2021-12-02 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezerwacje', '0005_auto_20211201_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='skype_login',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
