# Generated by Django 3.2.3 on 2021-12-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezerwacje', '0006_user_skype_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifycodeemployeeregistration',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='verify code used'),
        ),
    ]
