# Generated by Django 3.2.3 on 2021-12-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezerwacje', '0008_alter_user_skype_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='skype_login',
            field=models.CharField(blank=True, error_messages={'unique': 'Wprowadzony login Skype jest już zajęty'}, max_length=100, null=True, unique=True),
        ),
    ]
