# Generated by Django 3.2.3 on 2021-12-21 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rezerwacje', '0009_alter_user_skype_login'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'Users'},
        ),
    ]
