# Generated by Django 3.2.3 on 2021-12-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezerwacje', '0010_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, error_messages={'unique': 'Wprowadzony numer telefonu już istnieje w bazie danych'}, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='skype_login',
            field=models.CharField(blank=True, error_messages={'unique': 'Wprowadzony login Skype jest już istnieje w bazie danychs'}, max_length=100, null=True, unique=True),
        ),
    ]
