# Generated by Django 3.2.3 on 2021-12-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezerwacje', '0011_auto_20211228_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, error_messages={'unique': 'Wprowadzony numer telefonu już istnieje w bazie danych'}, max_length=20, null=True, unique=True, verbose_name='Numer telefonu'),
        ),
    ]
